services:
  - type: web
    name: ludogamenet-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
    healthCheckPath: /health
